#ifndef PRIVACY_HTTP_SDK_VERSION_H
#define PRIVACY_HTTP_SDK_VERSION_H

#define PRIVACY_HTTP_SDK_VERSION_MAJOR @PROJECT_VERSION_MAJOR@
#define PRIVACY_HTTP_SDK_VERSION_MINOR @PROJECT_VERSION_MINOR@
#define PRIVACY_HTTP_SDK_VERSION_PATCH @PROJECT_VERSION_PATCH@

#define PRIVACY_HTTP_SDK_VERSION "@PROJECT_VERSION@"

#endif // PRIVACY_HTTP_SDK_VERSION_H
