name: Build C++ Module

on:
  workflow_dispatch:
  push:
    paths:
      - '**/*'
  pull_request:
    paths:
      - '**/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake build-essential

      - name: List files in http-c++ directory (for debugging)
        run: ls -R http-c++

      - name: Create build directory and configure CMake
        run: |
          mkdir -p http-c++/build
          cmake -S http-c++ -B http-c++/build

      - name: Build C++ project
        run: cmake --build http-c++/build

