name: C/C++ CI with Rust Library

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4  # Checkout the main repository

    # Install dependencies including Rust, CMake, and build-essential
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake libclang-dev
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y  # Install Rust

    # Set up Rust environment
    - name: Set up Rust
      run: source $HOME/.cargo/env

    # Build the Rust library (assuming it's in the current directory)
    - name: Build Rust library
      run: |
        cargo build --release  # Build the Rust shared library

    # Build the C++ project using CMake (assuming the C++ files are in the root)
    - name: Build C++ project
      run: |
        cmake .
        make

    # Run any tests (optional, depending on your project setup)
    - name: Run tests (if any)
      run: make test  # You may replace this with your own test command

    # Run any additional checks (optional)
    - name: Run make distcheck (optional)
      run: make distcheck
